### ISSUE TITLE
Pestle Not Working?

### ISSUE THREAD

**Issue by astormnewrelic** [fballiano/homebrew-mageutils#2]
I'm on MacOS 10.14.6 and this happens when I try to run the brew installed pestle

    $ pestle
    PHP Fatal error:  Uncaught UnexpectedValueException:    RecursiveDirectoryIterator::__construct(/Users/astorm/pestle _modules/modules/): failed to open dir: No such file or directory in phar:///usr/local/Cellar/pestle/1.5.0/bin/pestle/modules/pulsestorm/cli/build_command_list/module.php:21

Before I dig into this, is this is known issue?  What would you need to reproduce/debug/fix this?

**Comment by astormnewrelic** [comment]
opened with wrong github account, please ignore.

**Comment by fballiano** [comment]
Hi @astormnewrelic! great pleasure to see you here!

In my Catalina peste is working fine:
```
fab@MacBook-Pro-di-Fabrizio ~/P/m2t> pestle 

                  _   _
                 | | | |
  _ __   ___  ___| |_| | ___
 | '_ \ / _ \/ __| __| |/ _ \
 | |_) |  __/\__ \ |_| |  __/
 | .__/ \___||___/\__|_|\___|
 | |
 |_|
pestle by Pulse Storm LLC
```

I wanted to tell you, I had to re-host the peste phar on my server because I needed to have the version number in the name, as you can see from the homebrew formula: https://github.com/fballiano/homebrew-mageutils/blob/master/Formula/pestle.rb but if you're interested in host all future versions of peste (with version in the file name) on your own server I'll be happy to direcly link/download them instead (also, it would make it more official). What do you think about that?

**Comment by astorm** [comment]
Thanks Fabrizio, [the problem was on my end](https://github.com/astorm/pestle/issues/509) -- I installed pestle on a laptop that had an older, in progress version of pestle installed (which I'd forgotten about).  Re: hosting it -- probably best to have your own source for this -- I'll still handle critical issues for pestle but generally speaking its in maintenance mode.
